version: '3.8'

services:
  db:
    env_file: ./.env
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    env_file: ./.env
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URI}

  seeder:
    env_file: ./.env
    build: .
    command: python seeds/seed.py
    depends_on:
      - db

volumes:
  postgres_data: